INSERT INTO cursos (nome, semestres) VALUES ("Ciência da Computação", 8);
INSERT INTO cursos (nome, semestres) VALUES ("Engenharia Elétrica", 10);
INSERT INTO cursos (nome, semestres) VALUES ("Matemática", 8);
INSERT INTO cursos (nome, semestres) VALUES ("Engenharia Mecânica", 11);

INSERT INTO departamentos (nome, chefe_id) VALUES ("Departamento Ciência da Computação", null);
INSERT INTO departamentos (nome, chefe_id) VALUES ("Departamento Engenharia Elétrica", null);
INSERT INTO departamentos (nome, chefe_id) VALUES ("Departamento Matemática", null);
INSERT INTO departamentos (nome, chefe_id) VALUES ("Departamento Engenharia Mecânica", null);

INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Heitor Mendes", "fernandocavalcanti@example.org", 8632.12, 2);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Bruno Mendonça", "uda-mota@example.net", 11055.43, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Alana Duarte", "luiz-fernandofernandes@example.org", 9554.53, 2);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Carolina Martins", "santosmariane@example.org", 9959.56, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Felipe da Costa", "monteiroheitor@example.org", 5546.99, 3);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Ravy Sales", "josebarbosa@example.net", 11444.28, 3);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Giovanna Andrade", "mda-conceicao@example.com", 9340.56, 2);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Ana Vitória Pires", "novaeserick@example.net", 4325.53, 4);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Larissa Melo", "qmoraes@example.net", 8775.20, 3);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Dr. Bryan Fernandes", "enzocaldeira@example.net", 3509.51, 3);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Felipe Oliveira", "migueljesus@example.com", 10580.94, 2);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Rodrigo Souza", "laura81@example.net", 7369.41, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Mariah Silva", "diasbento@example.com", 10244.60, 3);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Maya Pacheco", "sda-cruz@example.net", 11968.31, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Allana Vieira", "fogacarafael@example.net", 3885.37, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Anthony Melo", "abreutheo@example.com", 7983.70, 2);

INSERT INTO alunos (nome, email) VALUES ("Luigi da Luz", "dcampos@example.org");
INSERT INTO alunos (nome, email) VALUES ("Srta. Maria Alice da Mata", "lucascardoso@example.org");
INSERT INTO alunos (nome, email) VALUES ("Ana Laura Caldeira", "vitor-gabriel40@example.net");
INSERT INTO alunos (nome, email) VALUES ("Raquel Almeida", "benjaminmartins@example.com");
INSERT INTO alunos (nome, email) VALUES ("Isadora Gonçalves", "onovaes@example.net");
INSERT INTO alunos (nome, email) VALUES ("João Gabriel Pastor", "zmontenegro@example.org");
INSERT INTO alunos (nome, email) VALUES ("Sra. Sarah Santos", "portoamanda@example.net");
INSERT INTO alunos (nome, email) VALUES ("Davi Lucca Souza", "joao-guilherme60@example.org");
INSERT INTO alunos (nome, email) VALUES ("Ana Lopes", "camargogael-henrique@example.com");
INSERT INTO alunos (nome, email) VALUES ("Dr. Leandro Lopes", "apollo99@example.com");
INSERT INTO alunos (nome, email) VALUES ("Ana Clara Fogaça", "erickmachado@example.org");
INSERT INTO alunos (nome, email) VALUES ("Benicio Vargas", "liviagoncalves@example.net");
INSERT INTO alunos (nome, email) VALUES ("Maria Luísa Dias", "anthonymendes@example.org");
INSERT INTO alunos (nome, email) VALUES ("Thales Câmara", "aandrade@example.com");
INSERT INTO alunos (nome, email) VALUES ("Srta. Sara Moura", "mandrade@example.org");
INSERT INTO alunos (nome, email) VALUES ("Ryan Oliveira", "andradeisabela@example.com");
INSERT INTO alunos (nome, email) VALUES ("Alícia Oliveira", "calebmartins@example.org");
INSERT INTO alunos (nome, email) VALUES ("Lorenzo da Rosa", "lribeiro@example.net");
INSERT INTO alunos (nome, email) VALUES ("Mariane Vieira", "habreu@example.org");
INSERT INTO alunos (nome, email) VALUES ("Dra. Bárbara Correia", "kamilly21@example.com");

INSERT INTO disciplinas (nome, curso_id) VALUES ("Banco de Dados", 1);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Física II", 4);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Mecânica dos Fluidos", 4);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Física I", 4);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Computação Movel", 1);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Geometria Analitica", 3);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Sistemas Digitais", 2);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Redes", 2);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Calculo I", 3);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Engenharia de Software", 1);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Engenheinharia de Tomadas", 2);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Desenvolvimento WEB", 1);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Sistemas Digitais II", 2);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Calculo II", 3);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Calculo III", 3);

INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (1, 1, 1, 2022);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (2, 2, 2, 2005);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (3, 3, 2, 2015);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (4, 4, 1, 2020);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (5, 5, 1, 2004);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (6, 6, 1, 2017);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (7, 7, 2, 2021);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (8, 8, 2, 2003);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (9, 9, 1, 2011);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (10, 10, 1, 2023);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (11, 11, 2, 2008);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (12, 12, 1, 2004);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (13, 13, 2, 2009);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (14, 14, 1, 2005);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (15, 15, 2, 2008);

INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (1, 10, 2, 2003, 9.85);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (2, 2, 1, 2021, 8.83);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (3, 5, 2, 2006, 1.31);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (4, 7, 1, 2004, 0.21);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (5, 11, 2, 2010, 9.27);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (6, 6, 1, 2013, 0.65);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (7, 2, 1, 2019, 5.13);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (8, 4, 2, 2014, 8.56);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (9, 12, 2, 2008, 5.43);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (10, 1, 1, 2004, 7.36);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (11, 4, 1, 2005, 3.42);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (12, 9, 2, 2003, 3.77);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (13, 12, 2, 2005, 7.16);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (14, 7, 2, 2019, 1.99);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (15, 6, 2, 2003, 6.64);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (16, 12, 2, 2002, 0.05);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (17, 15, 1, 2004, 7.67);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (18, 3, 2, 2011, 5.00);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (19, 2, 1, 2018, 1.42);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (20, 12, 1, 2014, 8.70);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (3, 11, 1, 2001, 9.45);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (17, 3, 1, 2012, 4.11);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (1, 11, 2, 2011, 1.42);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (20, 6, 2, 2014, 5.99);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (17, 13, 1, 2006, 9.00);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (3, 12, 1, 2021, 9.83);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (8, 13, 2, 2003, 4.01);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (12, 3, 2, 2007, 7.11);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (18, 9, 2, 2011, 8.51);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (21, 13, 1, 2023, 0.26);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (21, 10, 2, 2013, 5.48);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (6, 1, 1, 2004, 6.15);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (3, 5, 2, 2021, 0.55);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (13, 13, 1, 2017, 5.07);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (2, 3, 1, 2007, 9.32);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (12, 2, 1, 2007, 5.54);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (14, 10, 1, 2006, 9.36);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (19, 11, 2, 2005, 8.06);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (14, 15, 2, 2005, 7.42);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (9, 1, 1, 2011, 8.37);

INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (1, 1, 3);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (2, 2, 4);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (3, 3, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (4, 4, 2);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (5, 5, 1);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (6, 6, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (7, 7, 4);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (8, 8, 1);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (9, 9, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (10, 10, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (11, 11, 1);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (12, 12, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (13, 13, 3);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (14, 14, 2);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (15, 15, 3);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (16, 16, 1);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (17, 1, 3);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (18, 2, 1);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (19, 3, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (20, 4, 5);

UPDATE departamentos SET chefe_id = 14 WHERE id = 1;
UPDATE departamentos SET chefe_id = 17 WHERE id = 2;
UPDATE departamentos SET chefe_id = 16 WHERE id = 3;
UPDATE departamentos SET chefe_id = 12 WHERE id = 4;
