INSERT INTO cursos (nome, semestres) VALUES ("Ciência da Computação", 8);
INSERT INTO cursos (nome, semestres) VALUES ("Engenharia Elétrica", 10);
INSERT INTO cursos (nome, semestres) VALUES ("Matemática", 8);
INSERT INTO cursos (nome, semestres) VALUES ("Engenharia Mecânica", 11);

INSERT INTO departamentos (nome, chefe_id) VALUES ("Departamento Ciência da Computação", null);
INSERT INTO departamentos (nome, chefe_id) VALUES ("Departamento Engenharia Elétrica", null);
INSERT INTO departamentos (nome, chefe_id) VALUES ("Departamento Matemática", null);
INSERT INTO departamentos (nome, chefe_id) VALUES ("Departamento Engenharia Mecânica", null);

INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Ísis Nunes", "castrovitoria@example.com", 10672.93, 4);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Daniela Ramos", "amanda82@example.com", 5571.63, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Bento Correia", "guerrafelipe@example.net", 6011.31, 4);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Dr. Lucas Casa Grande", "coliveira@example.com", 5248.17, 4);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Davi Lucca Nunes", "ygarcia@example.org", 5805.20, 2);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Allana Dias", "ialves@example.org", 5198.12, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Marcela da Luz", "juancaldeira@example.org", 7259.74, 4);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Allana Oliveira", "vsiqueira@example.org", 5125.58, 4);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Sra. Gabriela Fernandes", "aylalima@example.org", 5958.48, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Antônio Vargas", "joao-lucas57@example.net", 10404.24, 4);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Leonardo Costa", "casa-grandehenry@example.org", 8638.79, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Sra. Eloá Pires", "thiago03@example.org", 9868.50, 2);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Theo da Paz", "gabrielasouza@example.net", 10803.28, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Pedro Lucas Souza", "oliviacamargo@example.net", 11367.86, 2);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Dr. Asafe Guerra", "theo94@example.org", 4525.13, 1);
INSERT INTO professores (nome, email, salario, departamento_id) VALUES ("Cecília da Costa", "cavalcantimaria-fernanda@example.org", 9885.00, 2);

INSERT INTO alunos (nome, email) VALUES ("Caleb Sousa", "antony12@example.com");
INSERT INTO alunos (nome, email) VALUES ("Carlos Eduardo Sales", "joao-gabrielda-rocha@example.com");
INSERT INTO alunos (nome, email) VALUES ("Luana Aragão", "calebelopes@example.org");
INSERT INTO alunos (nome, email) VALUES ("Srta. Stella Oliveira", "miguelcassiano@example.net");
INSERT INTO alunos (nome, email) VALUES ("Gabriela Castro", "evelynda-conceicao@example.org");
INSERT INTO alunos (nome, email) VALUES ("Aurora Lima", "gmachado@example.net");
INSERT INTO alunos (nome, email) VALUES ("Rebeca Aparecida", "cardosopietra@example.net");
INSERT INTO alunos (nome, email) VALUES ("Leonardo Andrade", "bcardoso@example.com");
INSERT INTO alunos (nome, email) VALUES ("Sra. Emilly Cavalcanti", "castroemilly@example.net");
INSERT INTO alunos (nome, email) VALUES ("Luiz Gustavo Moreira", "ycirino@example.com");
INSERT INTO alunos (nome, email) VALUES ("Isis Silva", "marcela12@example.com");
INSERT INTO alunos (nome, email) VALUES ("Stephany Sampaio", "francisconogueira@example.net");
INSERT INTO alunos (nome, email) VALUES ("Raul Barros", "dduarte@example.org");
INSERT INTO alunos (nome, email) VALUES ("Srta. Antonella Costa", "eloafernandes@example.com");
INSERT INTO alunos (nome, email) VALUES ("Léo Gonçalves", "macedoemanuella@example.net");
INSERT INTO alunos (nome, email) VALUES ("Vitor Ribeiro", "vda-luz@example.org");
INSERT INTO alunos (nome, email) VALUES ("Dr. Daniel Jesus", "da-rosamaria-liz@example.net");
INSERT INTO alunos (nome, email) VALUES ("Isaac Aparecida", "nina35@example.net");
INSERT INTO alunos (nome, email) VALUES ("Samuel Cunha", "joao-guilherme05@example.net");
INSERT INTO alunos (nome, email) VALUES ("Brayan Monteiro", "ana-juliagarcia@example.com");

INSERT INTO disciplinas (nome, curso_id) VALUES ("Banco de Dados", 1);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Física II", 4);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Mecânica dos Fluidos", 4);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Física I", 4);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Computação Movel", 1);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Geometria Analitica", 3);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Sistemas Digitais", 2);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Redes", 2);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Calculo I", 3);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Engenharia de Software", 1);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Engenheinharia de Tomadas", 2);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Desenvolvimento WEB", 1);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Sistemas Digitais II", 2);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Calculo II", 3);
INSERT INTO disciplinas (nome, curso_id) VALUES ("Calculo III", 3);

INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (1, 1, 2, 2000);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (2, 2, 1, 2005);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (3, 3, 1, 2001);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (4, 4, 1, 2001);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (5, 5, 1, 2004);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (6, 6, 1, 2024);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (7, 7, 1, 2009);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (8, 8, 1, 2009);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (9, 9, 2, 2011);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (10, 10, 1, 2006);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (11, 11, 2, 2012);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (12, 12, 1, 2015);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (13, 13, 1, 2018);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (14, 14, 1, 2023);
INSERT INTO disciplinas_ministradas (professor_id, disciplina_id, semestre, ano) VALUES (15, 15, 2, 2018);

INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (1, 6, 1, 2022, 3.62);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (2, 1, 1, 2013, 9.83);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (3, 10, 1, 2023, 7.84);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (4, 13, 1, 2019, 1.32);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (5, 9, 1, 2017, 3.64);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (6, 7, 2, 2017, 1.28);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (7, 8, 1, 2014, 3.31);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (8, 1, 2, 2021, 7.82);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (9, 9, 1, 2010, 6.39);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (10, 3, 2, 2011, 0.96);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (11, 4, 1, 2024, 4.24);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (12, 4, 2, 2011, 9.33);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (13, 4, 2, 2020, 9.11);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (14, 11, 2, 2021, 3.75);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (15, 7, 1, 2003, 1.49);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (16, 8, 2, 2018, 1.87);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (17, 5, 1, 2010, 0.33);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (18, 10, 2, 2003, 6.46);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (19, 14, 2, 2019, 6.77);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (20, 6, 2, 2015, 4.79);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (17, 4, 1, 2006, 2.05);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (13, 8, 2, 2005, 2.19);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (1, 5, 1, 2007, 4.73);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (14, 10, 1, 2024, 6.95);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (7, 9, 2, 2009, 8.07);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (12, 10, 2, 2011, 2.79);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (11, 12, 1, 2013, 9.61);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (20, 8, 1, 2016, 8.95);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (13, 4, 2, 2006, 2.98);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (8, 4, 1, 2012, 2.01);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (1, 10, 1, 2009, 7.67);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (20, 10, 2, 2014, 6.25);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (12, 15, 2, 2002, 4.03);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (21, 7, 1, 2017, 1.16);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (6, 7, 1, 2004, 5.00);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (4, 6, 1, 2009, 5.56);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (21, 4, 2, 2008, 2.58);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (9, 2, 1, 2011, 1.47);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (13, 6, 1, 2011, 0.56);
INSERT INTO alunos_cursou (aluno_id, disciplina_id, semestre, ano, nota) VALUES (7, 5, 2, 2018, 7.74);

INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (1, 1, 4);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (2, 2, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (3, 3, 1);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (4, 4, 3);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (5, 5, 4);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (6, 6, 3);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (7, 7, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (8, 8, 2);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (9, 9, 3);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (10, 10, 1);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (11, 11, 3);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (12, 12, 3);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (13, 13, 1);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (14, 14, 2);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (15, 15, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (16, 16, 4);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (17, 1, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (18, 2, 1);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (19, 3, 5);
INSERT INTO alunos_tcc (aluno_id, orientador_id, grupo) VALUES (20, 4, 3);
